### ISSUE TITLE
I encountered a problem while make ops

### ISSUE THREAD

**Issue by Kevinstiff** [Johnqczhang/densepose_installation#10]
**Main error message:**
/usr/bin/ld: cannot find -lcaffe2_library
/usr/bin/ld: cannot find -lcaffe2_gpu_library

(caffe2) kevin@ubuntu:~/project/DensePose$ make ops
mkdir -p build && cd build && cmake .. && make -j8
-- Caffe2: CUDA detected: 10.1
-- Caffe2: CUDA nvcc is: /usr/local/cuda-10.1/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-10.1
-- Caffe2: Header version is: 10.1
-- Found cuDNN: v7.6.5 (include: /usr/local/cuda-10.1/include, library: /usr/local/cuda-10.1/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s): 7.5 7.5
-- Added CUDA NVCC flags for: -gencode;arch=compute_75,code=sm_75
-- Summary:
-- CMake version : 3.5.1
-- CMake command : /usr/bin/cmake
-- System name : Linux
-- C++ compiler : /usr/bin/c++
-- C++ compiler version : 5.4.0
-- CXX flags : -std=c++14 -O2 -fPIC -Wno-narrowing
-- Caffe2 version : 1.4.0
-- Caffe2 include path : /home/kevin/anaconda3/envs/caffe2/lib/python2.7/site-packages/torch/include
-- Caffe2 found CUDA : True
-- CUDA version : 10.1
-- CuDNN version : 7.6.5
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kevin/project/DensePose/build
make[1]: Entering directory '/home/kevin/project/DensePose/build'
make[2]: Entering directory '/home/kevin/project/DensePose/build'
make[3]: Entering directory '/home/kevin/project/DensePose/build'
make[3]: Leaving directory '/home/kevin/project/DensePose/build'
make[3]: Entering directory '/home/kevin/project/DensePose/build'
make[3]: Entering directory '/home/kevin/project/DensePose/build'
[ 12%] Linking CXX shared library libcaffe2_detectron_custom_ops.so
make[3]: Leaving directory '/home/kevin/project/DensePose/build'
make[3]: Entering directory '/home/kevin/project/DensePose/build'
**/usr/bin/ld: cannot find -lcaffe2_library**
[ 25%] Linking CXX shared library libcaffe2_detectron_custom_ops_gpu.so
collect2: error: ld returned 1 exit status
CMakeFiles/caffe2_detectron_custom_ops.dir/build.make:120: recipe for target 'libcaffe2_detectron_custom_ops.so' failed
make[3]: *** [libcaffe2_detectron_custom_ops.so] Error 1
make[3]: Leaving directory '/home/kevin/project/DensePose/build'
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops.dir/all' failed
make[2]: *** [CMakeFiles/caffe2_detectron_custom_ops.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
**/usr/bin/ld: cannot find -lcaffe2_gpu_library**
collect2: error: ld returned 1 exit status
CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/build.make:1335: recipe for target 'libcaffe2_detectron_custom_ops_gpu.so' failed
make[3]: *** [libcaffe2_detectron_custom_ops_gpu.so] Error 1
make[3]: Leaving directory '/home/kevin/project/DensePose/build'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/all' failed
make[2]: *** [CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/all] Error 2
make[2]: Leaving directory '/home/kevin/project/DensePose/build'
Makefile:127: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/kevin/project/DensePose/build'
Makefile:13: recipe for target 'ops' failed
make: *** [ops] Error 2

**Comment by Johnqczhang** [comment]
Hi @Kevinstiff, sorry for the late reply. I saw your issue has been solved by @linkinpark213's solution from [here](https://github.com/linkinpark213/linkinpark213.github.io/issues/12#issuecomment-566343452), so I'll close this issue.
Hi @linkinpark213, thanks for your help!
